services:
  llm:
    build: ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

  go-api:
    build: .
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on:
      - llm
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - LLM_MODEL=llama3.2
    restart: unless-stopped

volumes:
  ollama_data:
