name: Build and Push Go Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Go image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/danielbutlerismyname/go-api:latest
            ghcr.io/danielbutlerismyname/go-api:${{ github.sha }}

      - name: Build and push Ollama image
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./ollama
          push: true
          tags: |
            ghcr.io/danielbutlerismyname/ollama-custom:latest
            ghcr.io/danielbutlerismyname/ollama-custom:${{ github.sha }}
